import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const [visibleCards, setVisibleCards] = useState([]);

  useEffect(() => {
    console.log("=== useeffect ===");
    const handleScroll = () => {
      const windowHeight = window.innerHeight;
      const cards = document.querySelectorAll('.card1');

      cards.forEach((card) => {
        const cardTop = card.getBoundingClientRect().top;
        console.log('windowHeight:', windowHeight);
        console.log('cardTop:', cardTop);

        if (cardTop < windowHeight) {
          console.log('cli');
          setVisibleCards((prevVisibleCards) => [...prevVisibleCards, card]);
          card.classList.add('card1');
        }
      });
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  });

  useEffect(() => {
    visibleCards.forEach((card) => {
      card.classList.add('fadeIn');
    });
  }, [visibleCards]);




  const [scrollPosition, setScrollPosition] = useState(0);
  function handleClick(id) {
    console.log('cli');
    const element = document.getElementById(id);
    const position = element.offsetTop - 70;
    setScrollPosition(position);
    window.scrollTo({
      top: position,
      behavior: 'smooth'
    });
  }



  return (
    <>
      <Head>
        <title>portfolio of kayakenko</title>
        <meta name="description" content="Generated by KK " />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.mainvisual} id='IMG'>
          <Image className={styles.imagen} src='/ab.png' alt="pick" loading="lazy" position="relative" width="2000" height="2000" ></Image>
        </div>

        <div className={styles.center}>
          <a className={styles.card1}>
            <h2 id="skills" className={styles.cardTitle}>Skills</h2>
            <div className={`${styles.cards} ${styles.fadeIn}`}>
              <p> HTML / CSS / Javascript / React</p>
              <p>TOEIC 725/990点</p>
              <p style={{marginTop: "10px"}}>DeepL等の翻訳ソフトを使いながらではありますが、</p>
              <p>公式ドキュメントを参考に調べながら開発を行うことができます。</p>
            </div>
          </a>

          <a className={styles.card2}>
            <h2 className={styles.cardTitle} id="background">Background</h2>
            <div className={styles.cards}>
              <div className={styles.schoolHistory}>
                <p className={styles.schoolHistoryTitle}>学歴</p>
                <div className={styles.schoolHistoryContent}>
                  <p style={{marginTop: "10px"}}>2018年3月：慶應義塾大学志木高校卒業</p>
                  <p>2023年3月：慶應義塾大学商学部卒業</p>
                </div>
              </div>
              <div className={styles.workHistory}>
                <p className={styles.workHistoryTitle}>職歴</p>
                <div className={styles.workHistoryContent}>
                  <p style={{marginTop: "10px"}}>2018年12月~現在</p>
                  <p style={{marginLeft: "10px"}}>株式会社日本入試センター</p>
                  <p style={{marginLeft: "10px"}}>SAPIXPrivatoにて非常勤務講師を担当。</p>
                  <p style={{marginTop: "10px"}}>2022年3月~2023年3月</p>
                  <p style={{marginLeft: "10px"}}>株式会社DONUTS</p>
                  <p style={{marginLeft: "10px"}}>ミクチャ事業部にて音響業務を担当。</p>
                  <p style={{marginTop: "10px"}}>現在</p>
                  <p style={{marginLeft: "10px"}}>求職中</p>
                </div>
              </div>
            </div>
          </a>


        </div>
        <aside className={styles.sideMenu}>
          <h2 className={styles.sideMenuTitle}></h2>
          <ul className={styles.sideMenuList}>


            <li className={styles.sideMenuItem}><a onClick={() => handleClick("skills")}>Skills</a></li>
            <li className={styles.sideMenuItem}><a onClick={() => handleClick("background")}>Background</a></li>
            <li className={styles.sideMenuItem}><a onClick={() => handleClick("IMG")}>Go back</a></li>
          </ul>
        </aside>
        <footer className={styles.footer}>
          <a href="https://twitter.com/kaya_awkmiu">
          <svg className={styles.footerItem} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/></svg>
          </a>

        </footer>
      </main>

    </>
  )
}
